server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/search_engine
    username: root
    password: root


indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://volochek.life/
      name: Volochek
    - url: https://www.svetlovka.ru/
      name: Svetlovka
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

jsoup-settings:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
  referrer: http://www.google.com