version: '3'
services:
  postgres:
    image: postgres:14.6-alpine
    container_name: search_engine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=search_engine
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root